apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-$COLOR_TEST
    environment: $COLOR_TEST
  name: frontend-$COLOR_TEST
  namespace: cadrart
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    io.kompose.service: frontend-$COLOR_TEST
    environment: $COLOR_TEST
status:
  loadBalancer: {}
