apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
    environment: $(ENVIRONMENT_COLOR)
  name: frontend
  namespace: cadrart-$(ENVIRONMENT)
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    io.kompose.service: frontend
    environment: $(ENVIRONMENT_COLOR)
status:
  loadBalancer: {}
