apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
    environment: blue
  name: frontend
  namespace: cadrart-a
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
      environment: blue
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/cadrart-default: 'true'
        io.kompose.service: frontend
        environment: blue
    spec:
      containers:
        - image: ghcr.io/manuszep/cadrart2025-frontend
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/www/static
              name: static-volume
      imagePullSecrets:
        - name: cadrart-registry-key
      restartPolicy: Always
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume-a
status: {}
