apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-$COLOR_TEST
    environment: $COLOR_TEST
  name: frontend-$COLOR_TEST
  namespace: cadrart
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-$COLOR_TEST
      environment: $COLOR_TEST
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/cadrart-default: 'true'
        io.kompose.service: frontend-$COLOR_TEST
        environment: $COLOR_TEST
    spec:
      containers:
        - image: ghcr.io/manuszep/cadrart2025-frontend
          imagePullPolicy: Always
          name: frontend-$COLOR_TEST
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "25m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - mountPath: /var/www/static
              name: static-volume
      imagePullSecrets:
        - name: cadrart-registry-key
      restartPolicy: Always
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume
status: {}
